version: '3.8'
 
services:
    node:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: "pointu_l/test_technique:1"
        networks:
            - backend_default
        volumes:
            - ./:/app:cached
        
        hostname: node
        working_dir: /app
        ports:
            - "8080:4444"
    
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        hostname: mysql
        networks:
            - backend_default
        restart: always
        volumes:
            - ./docker/database:/var/lib/mysql:cached
        environment:
            MYSQL_ROOT_PASSWORD: "default"


networks:
    backend_default: